"""expert graph refactor: split turn_summaries JSONB + tighten unique constraints

Revision ID: 08ff22eacf7f
Revises: 3a8369c7c148
Create Date: 2026-06-30 09:32:31.986767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08ff22eacf7f'
down_revision: Union[str, None] = '3a8369c7c148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # turn_summaries.summary 上的 GIN trigram 索引依赖 pg_trgm 扩展。
    # 部署环境(本地 docker + 线上 PG 镜像)若尚未启用,显式创建;
    # IF NOT EXISTS 兼容已启用场景幂等。
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table('turn_summaries',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_turn_summaries_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turn_summaries')),
    sa.UniqueConstraint('session_id', 'turn_number', name='uq_turn_summaries_session_turn')
    )
    op.create_index('idx_ts_summary_trgm', 'turn_summaries', ['summary'], unique=False, postgresql_using='gin', postgresql_ops={'summary': 'gin_trgm_ops'})
    op.create_index(op.f('ix_turn_summaries_session_id'), 'turn_summaries', ['session_id'], unique=False)

    # --- 数据迁移(autogenerate 不生成,手工补;PG JSONB 元素展开是 text() 唯一允许的例外)---
    # 把 rolling_summaries.turn_summaries JSONB 中的元素逐条搬到新表。
    # ON CONFLICT DO NOTHING 防重跑产生约束冲突;旧数据若 turn_number 重复,后入的丢。
    op.execute(
        """
        INSERT INTO turn_summaries (session_id, turn_number, summary, created_at)
        SELECT
            rs.session_id,
            (elem->>'turn_number')::int,
            elem->>'summary',
            COALESCE(
                NULLIF(elem->>'created_at', '')::timestamptz,
                rs.created_at
            )
        FROM rolling_summaries rs,
             jsonb_array_elements(rs.turn_summaries) AS elem
        WHERE rs.turn_summaries IS NOT NULL
        ON CONFLICT (session_id, turn_number) DO NOTHING
        """
    )

    op.drop_index(op.f('idx_audit_session'), table_name='audit_records')
    op.create_unique_constraint('uq_audit_records_session_turn', 'audit_records', ['session_id', 'turn_number'])
    op.drop_index(op.f('idx_reports_child'), table_name='daily_reports')
    op.drop_index(op.f('idx_reports_session'), table_name='daily_reports')
    op.create_unique_constraint('uq_daily_reports_child_user_id_report_date', 'daily_reports', ['child_user_id', 'report_date'])
    op.create_unique_constraint(op.f('uq_daily_reports_session_id'), 'daily_reports', ['session_id'])
    op.alter_column('rolling_summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('rolling_summaries', 'turn_summaries')
    op.create_index('idx_sessions_created_at', 'sessions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sessions_created_at', table_name='sessions')

    # 先把 JSONB 列加回(否则后续 UPDATE 拿不到目标列)
    op.add_column('rolling_summaries', sa.Column('turn_summaries', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='list[TurnSummaryEntry] JSON:每轮客观中立短摘要(turn + summary);供主对话图超窗压缩时注入主 LLM;日终专家时序分析直接读 audit_records.dimension_scores 原始数据,更精细'))

    # --- 数据回迁:把 turn_summaries 行重新聚为 JSONB 灌回 rolling_summaries.turn_summaries ---
    op.execute(
        """
        UPDATE rolling_summaries rs
        SET turn_summaries = COALESCE(rs.turn_summaries, '[]'::jsonb)
                  || COALESCE(
                      (
                          SELECT jsonb_agg(
                              jsonb_build_object(
                                  'turn_number', ts.turn_number,
                                  'summary', ts.summary,
                                  'created_at', to_char(ts.created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
                              ) ORDER BY ts.turn_number
                          )
                          FROM turn_summaries ts
                          WHERE ts.session_id = rs.session_id
                      ),
                      '[]'::jsonb
                  )
        """
    )

    op.drop_constraint(op.f('uq_daily_reports_session_id'), 'daily_reports', type_='unique')
    op.drop_constraint('uq_daily_reports_child_user_id_report_date', 'daily_reports', type_='unique')
    op.create_index(op.f('idx_reports_session'), 'daily_reports', ['session_id'], unique=True)
    op.create_index(op.f('idx_reports_child'), 'daily_reports', ['child_user_id', 'report_date'], unique=True)
    op.drop_constraint('uq_audit_records_session_turn', 'audit_records', type_='unique')
    op.create_index(op.f('idx_audit_session'), 'audit_records', ['session_id', 'turn_number'], unique=False)
    op.alter_column('rolling_summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_turn_summaries_session_id'), table_name='turn_summaries')
    op.drop_index('idx_ts_summary_trgm', table_name='turn_summaries', postgresql_using='gin', postgresql_ops={'summary': 'gin_trgm_ops'})
    op.drop_table('turn_summaries')
    # ### end Alembic commands ###
