"""m11_daily_reports_add_degraded_and_unique_index

Revision ID: 102b0ce35a1e
Revises: c0e2a1ba8009
Create Date: 2026-06-23 16:01:44.756521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '102b0ce35a1e'
down_revision: Union[str, None] = 'c0e2a1ba8009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_records', 'target_message_id',
               existing_type=sa.UUID(),
               comment='被审查的 ai_msg id(本轮审查锚点),由 enqueue_audit 从 me.py generator 传入',
               existing_comment='被审查的 ai_msg id（本轮审查锚点）。M9 新增，由 enqueue_audit 从 me.py generator 传入',
               existing_nullable=True)
    op.alter_column('audit_records', 'dimension_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='AuditDimensionScores JSON:6 维度 score(0-9) + detail;供日终专家按维度诊断与跨日聚合;需要综合分时由代码派生 max(score),不单独存储',
               existing_comment='AuditDimensionScores JSON：7 维度 score(0-9) + detail；供日终专家按维度诊断与跨日聚合；需要综合分时由代码派生 max(score)，不单独存储',
               existing_nullable=True)
    op.alter_column('auth_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='NULL = 永不过期(子账号)',
               existing_comment='NULL = 永不过期（子账号）',
               existing_nullable=True)
    op.alter_column('auth_tokens', 'device_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='审计用:{ua, ip, platform}',
               existing_comment='审计用：{ua, ip, platform}',
               existing_nullable=True)
    op.alter_column('child_profiles', 'created_by',
               existing_type=sa.UUID(),
               comment='创建者(审计用途;权限通过 family_id 控制)',
               existing_comment='创建者（审计用途；权限通过 family_id 控制）',
               existing_nullable=False)
    op.alter_column('child_profiles', 'birth_date',
               existing_type=sa.DATE(),
               comment='家长输入 age,存 today - age years',
               existing_comment='家长输入 age，存 today - age years',
               existing_nullable=False)
    op.alter_column('child_profiles', 'nickname',
               existing_type=sa.VARCHAR(length=12),
               comment='家长设置的子女昵称,长度 1-12',
               existing_comment='家长设置的子女昵称，B1 占位，B3 替换为 payload.nickname',
               existing_nullable=False)
    op.alter_column('child_profiles', 'concerns',
               existing_type=sa.TEXT(),
               comment='家长自然语言描述的关注点,注入审查提示词与日终专家提示词',
               existing_comment='家长自然语言描述的关注点，注入审查提示词和日终专家提示词',
               existing_nullable=True)
    op.alter_column('child_profiles', 'sensitivity',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='SensitivityConfig JSON,6 维度 0-9(默认 5)',
               existing_comment='SensitivityConfig JSON，7 维度 0-9（默认 5）',
               existing_nullable=True)
    op.alter_column('child_profiles', 'custom_redlines',
               existing_type=sa.TEXT(),
               comment='家长自然语言描述的红线话题,审查 Agent 作为 0/1 判定条件,命中触发温和转移并通知家长',
               existing_comment='家长自然语言描述的红线话题，审查 Agent 作为 0/1 判定条件，命中触发三级接管（温和转移）+ 通知家长',
               existing_nullable=True)
    op.add_column('daily_reports', sa.Column('degraded', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True 表示降级产物（交卷耗尽 / token 超限），前端展示降级提示'))
    op.alter_column('daily_reports', 'report_date',
               existing_type=sa.DATE(),
               comment='对齐 4 点逻辑日（boundary_hour=4）',
               existing_nullable=False)
    op.alter_column('daily_reports', 'overall_status',
               existing_type=postgresql.ENUM('stable', 'attention', 'alert', name='dailystatus'),
               comment='LLM 判断 + 危机态代码地板的当日整体状态(stable/attention/alert),UI 列表页色彩标识依据',
               existing_comment='LLM 综合判断的当日整体状态（stable/attention/alert），UI 列表页色彩标识依据',
               existing_nullable=False)
    op.alter_column('daily_reports', 'dimension_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='DailyDimensionSummary JSON:6 维度当日 peak / mean / high_ratio;代码层从 audit_records.dimension_scores 聚合,供 UI 雷达图 + 跨日对比使用',
               existing_comment='DailyDimensionSummary JSON：7 维度当日 peak / mean / high_turns；代码层从 audit_records.dimension_scores 聚合，供 LLM 量化锚点 + UI 雷达图 + 跨日对比',
               existing_nullable=True)
    op.drop_index(op.f('idx_reports_child'), table_name='daily_reports')
    op.create_index('idx_reports_child', 'daily_reports', ['child_user_id', 'report_date'], unique=True)
    op.alter_column('data_deletion_requests', 'child_id_snapshot',
               existing_type=sa.UUID(),
               comment='被删 child 的 user.id(快照)',
               existing_comment='被删 child 的 user.id（快照）',
               existing_nullable=False)
    op.alter_column('data_deletion_requests', 'reason',
               existing_type=sa.VARCHAR(length=50),
               comment='触发原因,固定 parent_request',
               existing_comment="触发原因，MVP 固定 'parent_request'",
               existing_nullable=False)
    op.alter_column('messages', 'intervention_type',
               existing_type=postgresql.ENUM('crisis', 'redline', 'guided', name='interventiontype'),
               comment='null=正常回复, crisis=危机接管, guided=二级注入后回复',
               existing_comment='null=正常回复, crisis=危机接管, redline=红线接管, guided=二级注入后回复',
               existing_nullable=True)
    op.alter_column('messages', 'turn_number',
               existing_type=sa.INTEGER(),
               comment='对话轮次编号。human/ai 同轮共享同号；summary 行与共同发送的 human 匹配。',
               existing_comment='对话轮次编号。human/ai 同轮共享同号；summary/discarded 行保持 0。由 Step 3 commit①/commit② 与 backfill SQL 共同维护',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'child_user_id',
               existing_type=sa.UUID(),
               comment='关联的 child(可选);child 删除时 CASCADE 清空,系统通知为 NULL',
               existing_comment='关联的 child（可选）；child 删除时 CASCADE 清空，系统通知为 NULL',
               existing_nullable=True)
    op.alter_column('notifications', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='代码层不约束 schema,消费方按 type 解构',
               existing_comment='MVP 不约束 schema，消费方按 type 解构',
               existing_nullable=True)
    op.alter_column('rolling_summaries', 'crisis_locked_message_id',
               existing_type=sa.UUID(),
               comment='crisis 粘性接管锚点消息 ID。非空=粘性锁定中,指向触发 crisis 的首条 ai_msg id;空=未锁定。session 内不可逆,仅开启新 session 可重置。',
               existing_comment='crisis 粘性接管锚点消息 ID。非空=粘性锁定中，指向触发 crisis 的首条 ai_msg id；空=未锁定。session 内不可逆，仅开启新 session 可重置。',
               existing_nullable=True)
    op.alter_column('rolling_summaries', 'session_notes',
               existing_type=sa.TEXT(),
               comment='风控视角的跨轮叙事笔记(TEXT),审查 Agent 按固定骨架整段重写维护:话题脉络 / 风险观察 / 情绪走向 / 家长关注点回应。供审查自身跨轮复用 + 日终专家生成家长报告;不注入主 LLM,避免风控判断泄漏',
               existing_comment='风控视角的跨轮叙事笔记（TEXT），审查 Agent 按固定骨架整段重写维护：话题脉络 / 风险观察 / 情绪走向 / 家长关注点回应。供审查自身跨轮复用 + 日终专家生成家长报告；不注入主 LLM，避免风控判断泄漏',
               existing_nullable=True)
    op.alter_column('rolling_summaries', 'turn_summaries',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='list[TurnSummaryEntry] JSON:每轮客观中立短摘要(turn + summary);供主对话图超窗压缩时注入主 LLM;日终专家时序分析直接读 audit_records.dimension_scores 原始数据,更精细',
               existing_comment='list[TurnSummaryEntry] JSON：每轮客观中立短摘要（turn + summary）；供主对话图超窗压缩时注入主 LLM；日终专家时序分析直接读 audit_records.dimension_scores 原始数据，更精细',
               existing_nullable=True)
    op.alter_column('sessions', 'context_size_tokens',
               existing_type=sa.INTEGER(),
               comment='末轮 LLM usage input_tokens + output_tokens 快照',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sessions', 'needs_compression',
               existing_type=sa.BOOLEAN(),
               comment='阈值命中 → True，下一轮 user 到达时阻塞压缩',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'consent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='监护人同意时间(仅 parent)',
               existing_comment='监护人同意时间（仅 parent）',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='argon2id 哈希,登录与 CLI 创建父账号时写入',
               existing_comment='argon2id 哈希，CLI / 登录时写入',
               existing_nullable=True)
    op.alter_column('users', 'admin_note',
               existing_type=sa.TEXT(),
               comment='运维备注,CLI --note 写入',
               existing_comment='运维备注，CLI --note 写入',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'admin_note',
               existing_type=sa.TEXT(),
               comment='运维备注，CLI --note 写入',
               existing_comment='运维备注,CLI --note 写入',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='argon2id 哈希，CLI / 登录时写入',
               existing_comment='argon2id 哈希,登录与 CLI 创建父账号时写入',
               existing_nullable=True)
    op.alter_column('users', 'consent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='监护人同意时间（仅 parent）',
               existing_comment='监护人同意时间(仅 parent)',
               existing_nullable=True)
    op.alter_column('sessions', 'needs_compression',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='阈值命中 → True，下一轮 user 到达时阻塞压缩',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('sessions', 'context_size_tokens',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='末轮 LLM usage input_tokens + output_tokens 快照',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('rolling_summaries', 'turn_summaries',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='list[TurnSummaryEntry] JSON：每轮客观中立短摘要（turn + summary）；供主对话图超窗压缩时注入主 LLM；日终专家时序分析直接读 audit_records.dimension_scores 原始数据，更精细',
               existing_comment='list[TurnSummaryEntry] JSON:每轮客观中立短摘要(turn + summary);供主对话图超窗压缩时注入主 LLM;日终专家时序分析直接读 audit_records.dimension_scores 原始数据,更精细',
               existing_nullable=True)
    op.alter_column('rolling_summaries', 'session_notes',
               existing_type=sa.TEXT(),
               comment='风控视角的跨轮叙事笔记（TEXT），审查 Agent 按固定骨架整段重写维护：话题脉络 / 风险观察 / 情绪走向 / 家长关注点回应。供审查自身跨轮复用 + 日终专家生成家长报告；不注入主 LLM，避免风控判断泄漏',
               existing_comment='风控视角的跨轮叙事笔记(TEXT),审查 Agent 按固定骨架整段重写维护:话题脉络 / 风险观察 / 情绪走向 / 家长关注点回应。供审查自身跨轮复用 + 日终专家生成家长报告;不注入主 LLM,避免风控判断泄漏',
               existing_nullable=True)
    op.alter_column('rolling_summaries', 'crisis_locked_message_id',
               existing_type=sa.UUID(),
               comment='crisis 粘性接管锚点消息 ID。非空=粘性锁定中，指向触发 crisis 的首条 ai_msg id；空=未锁定。session 内不可逆，仅开启新 session 可重置。',
               existing_comment='crisis 粘性接管锚点消息 ID。非空=粘性锁定中,指向触发 crisis 的首条 ai_msg id;空=未锁定。session 内不可逆,仅开启新 session 可重置。',
               existing_nullable=True)
    op.alter_column('notifications', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='MVP 不约束 schema，消费方按 type 解构',
               existing_comment='代码层不约束 schema,消费方按 type 解构',
               existing_nullable=True)
    op.alter_column('notifications', 'child_user_id',
               existing_type=sa.UUID(),
               comment='关联的 child（可选）；child 删除时 CASCADE 清空，系统通知为 NULL',
               existing_comment='关联的 child(可选);child 删除时 CASCADE 清空,系统通知为 NULL',
               existing_nullable=True)
    op.alter_column('messages', 'turn_number',
               existing_type=sa.INTEGER(),
               comment='对话轮次编号。human/ai 同轮共享同号；summary/discarded 行保持 0。由 Step 3 commit①/commit② 与 backfill SQL 共同维护',
               existing_comment='对话轮次编号。human/ai 同轮共享同号；summary 行与共同发送的 human 匹配。',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('messages', 'intervention_type',
               existing_type=postgresql.ENUM('crisis', 'redline', 'guided', name='interventiontype'),
               comment='null=正常回复, crisis=危机接管, redline=红线接管, guided=二级注入后回复',
               existing_comment='null=正常回复, crisis=危机接管, guided=二级注入后回复',
               existing_nullable=True)
    op.alter_column('data_deletion_requests', 'reason',
               existing_type=sa.VARCHAR(length=50),
               comment="触发原因，MVP 固定 'parent_request'",
               existing_comment='触发原因,固定 parent_request',
               existing_nullable=False)
    op.alter_column('data_deletion_requests', 'child_id_snapshot',
               existing_type=sa.UUID(),
               comment='被删 child 的 user.id（快照）',
               existing_comment='被删 child 的 user.id(快照)',
               existing_nullable=False)
    op.drop_index('idx_reports_child', table_name='daily_reports')
    op.create_index(op.f('idx_reports_child'), 'daily_reports', ['child_user_id', 'report_date'], unique=False)
    op.alter_column('daily_reports', 'dimension_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='DailyDimensionSummary JSON：7 维度当日 peak / mean / high_turns；代码层从 audit_records.dimension_scores 聚合，供 LLM 量化锚点 + UI 雷达图 + 跨日对比',
               existing_comment='DailyDimensionSummary JSON:6 维度当日 peak / mean / high_ratio;代码层从 audit_records.dimension_scores 聚合,供 UI 雷达图 + 跨日对比使用',
               existing_nullable=True)
    op.alter_column('daily_reports', 'overall_status',
               existing_type=postgresql.ENUM('stable', 'attention', 'alert', name='dailystatus'),
               comment='LLM 综合判断的当日整体状态（stable/attention/alert），UI 列表页色彩标识依据',
               existing_comment='LLM 判断 + 危机态代码地板的当日整体状态(stable/attention/alert),UI 列表页色彩标识依据',
               existing_nullable=False)
    op.alter_column('daily_reports', 'report_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='对齐 4 点逻辑日（boundary_hour=4）',
               existing_nullable=False)
    op.drop_column('daily_reports', 'degraded')
    op.alter_column('child_profiles', 'custom_redlines',
               existing_type=sa.TEXT(),
               comment='家长自然语言描述的红线话题，审查 Agent 作为 0/1 判定条件，命中触发三级接管（温和转移）+ 通知家长',
               existing_comment='家长自然语言描述的红线话题,审查 Agent 作为 0/1 判定条件,命中触发温和转移并通知家长',
               existing_nullable=True)
    op.alter_column('child_profiles', 'sensitivity',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='SensitivityConfig JSON，7 维度 0-9（默认 5）',
               existing_comment='SensitivityConfig JSON,6 维度 0-9(默认 5)',
               existing_nullable=True)
    op.alter_column('child_profiles', 'concerns',
               existing_type=sa.TEXT(),
               comment='家长自然语言描述的关注点，注入审查提示词和日终专家提示词',
               existing_comment='家长自然语言描述的关注点,注入审查提示词与日终专家提示词',
               existing_nullable=True)
    op.alter_column('child_profiles', 'nickname',
               existing_type=sa.VARCHAR(length=12),
               comment='家长设置的子女昵称，B1 占位，B3 替换为 payload.nickname',
               existing_comment='家长设置的子女昵称,长度 1-12',
               existing_nullable=False)
    op.alter_column('child_profiles', 'birth_date',
               existing_type=sa.DATE(),
               comment='家长输入 age，存 today - age years',
               existing_comment='家长输入 age,存 today - age years',
               existing_nullable=False)
    op.alter_column('child_profiles', 'created_by',
               existing_type=sa.UUID(),
               comment='创建者（审计用途；权限通过 family_id 控制）',
               existing_comment='创建者(审计用途;权限通过 family_id 控制)',
               existing_nullable=False)
    op.alter_column('auth_tokens', 'device_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='审计用：{ua, ip, platform}',
               existing_comment='审计用:{ua, ip, platform}',
               existing_nullable=True)
    op.alter_column('auth_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='NULL = 永不过期（子账号）',
               existing_comment='NULL = 永不过期(子账号)',
               existing_nullable=True)
    op.alter_column('audit_records', 'dimension_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='AuditDimensionScores JSON：7 维度 score(0-9) + detail；供日终专家按维度诊断与跨日聚合；需要综合分时由代码派生 max(score)，不单独存储',
               existing_comment='AuditDimensionScores JSON:6 维度 score(0-9) + detail;供日终专家按维度诊断与跨日聚合;需要综合分时由代码派生 max(score),不单独存储',
               existing_nullable=True)
    op.alter_column('audit_records', 'target_message_id',
               existing_type=sa.UUID(),
               comment='被审查的 ai_msg id（本轮审查锚点）。M9 新增，由 enqueue_audit 从 me.py generator 传入',
               existing_comment='被审查的 ai_msg id(本轮审查锚点),由 enqueue_audit 从 me.py generator 传入',
               existing_nullable=True)
    # ### end Alembic commands ###
