"""add auth_tokens indexes (token_hash unique + user_id partial active)

Revision ID: 3522d5e7ba69
Revises: 1d8a14cc596f
Create Date: 2026-04-28 03:03:40.657593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3522d5e7ba69'
down_revision: Union[str, None] = '1d8a14cc596f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_auth_tokens_token_hash', 'auth_tokens', ['token_hash'], unique=True)
    op.create_index('ix_auth_tokens_user_id_active', 'auth_tokens', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_tokens_user_id_active', table_name='auth_tokens', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_auth_tokens_token_hash', table_name='auth_tokens')
    # ### end Alembic commands ###
