"""add daily_reports updated_at

Revision ID: 3a8369c7c148
Revises: eb15ea6bc38f
Create Date: 2026-06-28 14:52:20.853723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a8369c7c148'
down_revision: Union[str, None] = 'eb15ea6bc38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='日报更新时间，多次写入时该时间与 created_at 不一致'))
    op.alter_column('daily_reports', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='报告送达时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_reports', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='报告送达时间',
               existing_nullable=True)
    op.drop_column('daily_reports', 'updated_at')
    # ### end Alembic commands ###
