"""initial schema: 12 tables

Revision ID: 5ab72cdbcaa8
Revises: 4b3f0332e1f4
Create Date: 2026-04-17 08:31:40.039888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ab72cdbcaa8'
down_revision: Union[str, None] = '4b3f0332e1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('sub_tier', sa.Enum('free', 'paid', name='subtier'), server_default='free', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('parent', 'child', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='仅父账号'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('consent_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='监护人同意时间（仅 parent）'),
    sa.Column('consent_version', sa.String(length=50), nullable=True, comment='同意的隐私政策版本'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='NULL = 永不过期（子账号）'),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='父账号解绑时写入'),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_profiles',
    sa.Column('child_user_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建者（审计用途；权限通过 family_id 控制）'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='家长输入 age，存近似生日 today - age years'),
    sa.Column('gender', sa.Enum('male', 'female', 'unknown', name='gender'), nullable=True),
    sa.Column('concerns', sa.Text(), nullable=True, comment='家长自然语言描述的关注点，注入审查提示词和日终专家提示词'),
    sa.Column('sensitivity', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='SensitivityConfig JSON，7 维度 0-9（默认 5）'),
    sa.Column('custom_redlines', sa.Text(), nullable=True, comment='家长自然语言描述的红线话题，审查 Agent 作为 0/1 判定条件，命中触发三级接管（温和转移）+ 通知家长'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_user_id')
    )
    op.create_table('daily_reports',
    sa.Column('child_user_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('overall_status', sa.Enum('stable', 'attention', 'alert', name='dailystatus'), nullable=False, comment='LLM 综合判断的当日整体状态（stable/attention/alert），UI 列表页色彩标识依据'),
    sa.Column('dimension_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='DailyDimensionSummary JSON：7 维度当日 peak / mean / high_turns；代码层从当日 audit_records.dimension_scores 聚合，供 LLM 量化锚点 + UI 雷达图 + 跨日对比'),
    sa.Column('content', sa.Text(), nullable=False, comment='markdown 格式报告'),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_child', 'daily_reports', ['child_user_id', 'report_date'], unique=False)
    op.create_table('data_deletion_requests',
    sa.Column('child_user_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False, comment='发起删除的家长'),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='deletionstatus'), server_default='pending', nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('ios', 'android', name='deviceplatform'), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('parent_user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('crisis', 'redline', 'daily_summary', name='notificationtype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('child_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'deleted', name='sessionstatus'), server_default='active', nullable=False),
    sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_child', 'sessions', ['child_user_id', 'status'], unique=False)
    op.create_table('audit_records',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AuditDimensionScores JSON：7 维度 score(0-9) + detail；供日终专家按维度诊断与跨日聚合；需要综合分时由代码派生 max(score)，不单独存储'),
    sa.Column('crisis_detected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('crisis_topic', sa.Text(), nullable=True),
    sa.Column('guidance_injection', sa.Text(), nullable=True, comment='注入的指引内容'),
    sa.Column('redline_triggered', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='家长红线命中 0/1'),
    sa.Column('redline_detail', sa.Text(), nullable=True, comment='命中的红线内容'),
    sa.Column('notify_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_session', 'audit_records', ['session_id', 'turn_number'], unique=False)
    op.create_table('messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('human', 'ai', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intervention_type', sa.Enum('crisis', 'redline', 'guided', name='interventiontype'), nullable=True, comment='null=正常回复, crisis=危机接管, redline=红线接管, guided=二级注入后回复'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_session', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_table('rolling_summaries',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('last_turn', sa.Integer(), nullable=False),
    sa.Column('crisis_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='crisis 粘性接管标志。一旦命中 crisis 置 true，该 session 剩余轮次全部由危机 LLM 接管；session 内不可逆，仅开启新 session 可重置。redline 不粘性，每轮重评估。'),
    sa.Column('session_notes', sa.Text(), nullable=True, comment='风控视角的跨轮叙事笔记（TEXT），审查 Agent 按固定骨架整段重写维护：话题脉络 / 风险观察 / 情绪走向 / 家长关注点回应。供审查自身跨轮复用 + 日终专家生成家长报告；不注入主 LLM，避免风控判断泄漏'),
    sa.Column('turn_summaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='list[TurnSummaryEntry] JSON：每轮客观中立短摘要（turn + summary）；供主对话图超窗压缩时注入主 LLM；日终专家时序分析直接读 audit_records.dimension_scores 原始数据，更精细'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rolling_summaries')
    op.drop_index('idx_messages_session', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_audit_session', table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index('idx_sessions_child', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('notifications')
    op.drop_table('device_tokens')
    op.drop_table('data_deletion_requests')
    op.drop_index('idx_reports_child', table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_table('child_profiles')
    op.drop_table('auth_tokens')
    op.drop_table('users')
    op.drop_table('families')
    # ### end Alembic commands ###
