"""m4: accounts auth fields and family_members

Revision ID: 5c162bd29a15
Revises: 5ab72cdbcaa8
Create Date: 2026-04-20 03:12:55.707434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c162bd29a15'
down_revision: Union[str, None] = '5ab72cdbcaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # family_members 建表：绕过 SQLAlchemy DDL event，避免重复 CREATE TYPE userrole
    op.execute(
        "CREATE TABLE family_members ("
        "  id UUID NOT NULL DEFAULT gen_random_uuid(),"
        "  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),"
        "  family_id UUID NOT NULL,"
        "  user_id UUID NOT NULL,"
        "  role userrole NOT NULL,"
        "  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),"
        "  PRIMARY KEY (id),"
        "  FOREIGN KEY (family_id) REFERENCES families(id),"
        "  FOREIGN KEY (user_id) REFERENCES users(id)"
        ")"
    )
    op.add_column('auth_tokens', sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='审计用：{ua, ip, platform}'))
    op.alter_column('auth_tokens', 'device_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('daily_reports', 'dimension_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='DailyDimensionSummary JSON：7 维度当日 peak / mean / high_turns；代码层从 audit_records.dimension_scores 聚合，供 LLM 量化锚点 + UI 雷达图 + 跨日对比',
               existing_comment='DailyDimensionSummary JSON：7 维度当日 peak / mean / high_turns；代码层从当日 audit_records.dimension_scores 聚合，供 LLM 量化锚点 + UI 雷达图 + 跨日对比',
               existing_nullable=True)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True, comment='argon2id 哈希，CLI / 登录时写入'))
    op.add_column('users', sa.Column('admin_note', sa.Text(), nullable=True, comment='运维备注，CLI --note 写入'))
    op.create_index('idx_users_phone_parent_active', 'users', ['phone'], unique=False, postgresql_where=sa.text("role = 'parent' AND is_active = true"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_phone_parent_active', table_name='users', postgresql_where=sa.text("role = 'parent' AND is_active = true"))
    op.drop_column('users', 'admin_note')
    op.drop_column('users', 'password_hash')
    op.alter_column('daily_reports', 'dimension_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='DailyDimensionSummary JSON：7 维度当日 peak / mean / high_turns；代码层从当日 audit_records.dimension_scores 聚合，供 LLM 量化锚点 + UI 雷达图 + 跨日对比',
               existing_comment='DailyDimensionSummary JSON：7 维度当日 peak / mean / high_turns；代码层从 audit_records.dimension_scores 聚合，供 LLM 量化锚点 + UI 雷达图 + 跨日对比',
               existing_nullable=True)
    op.alter_column('auth_tokens', 'device_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('auth_tokens', 'device_info')
    op.execute("DROP TABLE family_members")
    # ### end Alembic commands ###
