"""reconcile comment 标点到半角

Revision ID: 9ca13584e3d6
Revises: 15f014ed2898
Create Date: 2026-06-24 06:26:59.569094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca13584e3d6'
down_revision: Union[str, None] = '15f014ed2898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_reports', 'report_date',
               existing_type=sa.DATE(),
               comment='对齐 4 点逻辑日(boundary_hour=4)',
               existing_comment='对齐 4 点逻辑日（boundary_hour=4）',
               existing_nullable=False)
    op.alter_column('daily_reports', 'degraded',
               existing_type=sa.BOOLEAN(),
               comment='True 表示降级产物(交卷耗尽 / token 超限),前端展示降级提示',
               existing_comment='True 表示降级产物（交卷耗尽 / token 超限），前端展示降级提示',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'turn_number',
               existing_type=sa.INTEGER(),
               comment='对话轮次编号.human/ai 同轮共享同号;summary 行与共同发送的 human 匹配.',
               existing_comment='对话轮次编号。human/ai 同轮共享同号；summary 行与共同发送的 human 匹配。',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rolling_summaries', 'crisis_locked_message_id',
               existing_type=sa.UUID(),
               comment='crisis 粘性接管锚点消息 ID.非空=粘性锁定中,指向触发 crisis 的首条 ai_msg id;空=未锁定. session 内不可逆,仅开启新 session 可重置.',
               existing_comment='crisis 粘性接管锚点消息 ID。非空=粘性锁定中,指向触发 crisis 的首条 ai_msg id;空=未锁定。session 内不可逆,仅开启新 session 可重置。',
               existing_nullable=True)
    op.alter_column('sessions', 'needs_compression',
               existing_type=sa.BOOLEAN(),
               comment='阈值命中 → True,下一轮 user 到达时阻塞压缩',
               existing_comment='阈值命中 → True，下一轮 user 到达时阻塞压缩',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('sessions', 'ai_turn_counter',
               existing_type=sa.INTEGER(),
               comment='LLM AI 回复累积轮次;persist_ai_turn 同事务 +1',
               existing_comment='LLM AI 回复累积轮次；persist_ai_turn 同事务 +1',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'ai_turn_counter',
               existing_type=sa.INTEGER(),
               comment='LLM AI 回复累积轮次；persist_ai_turn 同事务 +1',
               existing_comment='LLM AI 回复累积轮次;persist_ai_turn 同事务 +1',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sessions', 'needs_compression',
               existing_type=sa.BOOLEAN(),
               comment='阈值命中 → True，下一轮 user 到达时阻塞压缩',
               existing_comment='阈值命中 → True,下一轮 user 到达时阻塞压缩',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('rolling_summaries', 'crisis_locked_message_id',
               existing_type=sa.UUID(),
               comment='crisis 粘性接管锚点消息 ID。非空=粘性锁定中,指向触发 crisis 的首条 ai_msg id;空=未锁定。session 内不可逆,仅开启新 session 可重置。',
               existing_comment='crisis 粘性接管锚点消息 ID.非空=粘性锁定中,指向触发 crisis 的首条 ai_msg id;空=未锁定. session 内不可逆,仅开启新 session 可重置.',
               existing_nullable=True)
    op.alter_column('messages', 'turn_number',
               existing_type=sa.INTEGER(),
               comment='对话轮次编号。human/ai 同轮共享同号；summary 行与共同发送的 human 匹配。',
               existing_comment='对话轮次编号.human/ai 同轮共享同号;summary 行与共同发送的 human 匹配.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_reports', 'degraded',
               existing_type=sa.BOOLEAN(),
               comment='True 表示降级产物（交卷耗尽 / token 超限），前端展示降级提示',
               existing_comment='True 表示降级产物(交卷耗尽 / token 超限),前端展示降级提示',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('daily_reports', 'report_date',
               existing_type=sa.DATE(),
               comment='对齐 4 点逻辑日（boundary_hour=4）',
               existing_comment='对齐 4 点逻辑日(boundary_hour=4)',
               existing_nullable=False)
    # ### end Alembic commands ###
