"""daily_report split content and add session_id

Revision ID: eb15ea6bc38f
Revises: 9ca13584e3d6
Create Date: 2026-06-24 12:48:29.909888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb15ea6bc38f'
down_revision: Union[str, None] = '9ca13584e3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('session_id', sa.UUID(), nullable=False, comment='锚定当日 chat session,删除 child 时级联清理'))
    op.add_column('daily_reports', sa.Column('today_overview', sa.Text(), nullable=False, comment='1. 今日概览:ExpertReportSchema.today_overview 直写'))
    op.add_column('daily_reports', sa.Column('what_was_discussed', sa.Text(), nullable=False, comment='2. 聊了什么:ExpertReportSchema.what_was_discussed 直写'))
    op.add_column('daily_reports', sa.Column('emotion_changes', sa.Text(), nullable=False, comment='3. 情绪变化:ExpertReportSchema.emotion_changes 直写'))
    op.add_column('daily_reports', sa.Column('noteworthy', sa.Text(), nullable=False, comment='4. 值得关注:ExpertReportSchema.noteworthy 直写'))
    op.add_column('daily_reports', sa.Column('suggestions', sa.Text(), nullable=False, comment='5. 具体建议:ExpertReportSchema.suggestions 直写'))
    op.add_column('daily_reports', sa.Column('anomaly_periods', sa.Text(), nullable=False, comment='6. 异常时段标注:ExpertReportSchema.anomaly_periods 直写'))
    op.create_index('idx_reports_session', 'daily_reports', ['session_id'], unique=True)
    op.create_foreign_key(op.f('fk_daily_reports_session_id_sessions'), 'daily_reports', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('daily_reports', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='markdown 格式报告'))
    op.drop_constraint(op.f('fk_daily_reports_session_id_sessions'), 'daily_reports', type_='foreignkey')
    op.drop_index('idx_reports_session', table_name='daily_reports')
    op.drop_column('daily_reports', 'anomaly_periods')
    op.drop_column('daily_reports', 'suggestions')
    op.drop_column('daily_reports', 'noteworthy')
    op.drop_column('daily_reports', 'emotion_changes')
    op.drop_column('daily_reports', 'what_was_discussed')
    op.drop_column('daily_reports', 'today_overview')
    op.drop_column('daily_reports', 'session_id')
    # ### end Alembic commands ###
