---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	load_context(load_context)
	audit_llm_call(audit_llm_call)
	audit_tools(audit_tools)
	write_results(write_results)
	__end__([<p>__end__</p>]):::last
	__start__ --> load_context;
	audit_llm_call -.-> audit_tools;
	audit_llm_call -.-> write_results;
	audit_tools -.-> audit_llm_call;
	audit_tools -.-> write_results;
	load_context --> audit_llm_call;
	write_results --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
